---
- name: Install Docker
  gather_facts: No
  become: yes
  hosts: testserver

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Install python pip
      package:
        name: python-pip
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user dev01 to docker group
      user:
        name: dev01
        groups: docker
        append: yes

    - name: Download and install Docker Compose
      shell: sudo pip install docker-py
    - name: Checking running Docker Container
      shell: docker ps -a
    - name: Starting the Nginx Docker Container
      docker_container:
       name: Nginx
       image: nginx:latest
       state: started
       restart: yes
       ports:
       - 80:80

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: yes

    - name: Download and install Docker Compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1

    - name: Give insecure permissions to docker-compose
      file: dest=/usr/local/bin/docker-compose owner=root group=root mode=775
     

    - name: Create a symbolic link
      file: src=/usr/local/bin/docker-compose  dest=/usr/bin/docker-compose    owner=root   group=root state=link  
