---
- include_vars: harden.yml

- name: Configure System Ctrl.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    ignoreerrors: yes
  with_items: "{{ harden }}"
