---
- hosts: testserver
  become: yes
  gather_facts: true

  pre_tasks:
  - name: Date Stamp # date/time stamp for when the playbook starts
    command: /bin/date
    register: timestamp_start
  - debug: var=timestamp_start #  
  - name: Start time
    raw: date > /tmp/time.log

  roles:
    - { role: ospatch, when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")  }

  post_tasks:
  - name: date/time stamp for when the playbook ends
    command: /bin/date
    register: timestamp_end
  - debug: var=timestamp_end    
  - name: Start time
    raw: date >> /tmp/time.log  
