---
- include: sshd.yml
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7" 
    
- include: package.yml
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
